import test from 'node:test';import assert from 'node:assert/strict';
import {attemptCapacity,budgetPlan,budgetStatus,canShowExhaustion} from '../assets/web/budget-view.js';
test('the visible allowance matches the unchanged conservative .05 attempt guard',()=>{assert.equal(attemptCapacity(.50),10);assert.equal(attemptCapacity(2),40);assert.equal(attemptCapacity(.30,.25),1);assert.equal(attemptCapacity(.10,.10),0);assert.equal(attemptCapacity(.10,.15),0);assert.equal(attemptCapacity(.008766667),0);assert.equal(attemptCapacity(NaN),null);});
test('completion estimates never replenish the displayed attempt allowance or become billing',()=>{const state={settings:{text_budget_usd:.10},text_reserved_usd:.10,estimated_text_usd:.0010275,text_busy:false};const before=structuredClone(state);const label=budgetStatus(state);assert.match(label,/осталось 0/);assert.match(label,/\$0.0010/);assert.match(label,/фактическое списание неизвестно/);assert.deepEqual(state,before);assert(!label.includes('выполняется'));assert.match(budgetStatus({...state,text_busy:true}),/Один запрос выполняется/);});
test('estimated preview states size dependent capacity and no invoice guarantee without authorizing anything',()=>{assert.match(budgetPlan(.50),/примерно 45/);assert.match(budgetPlan(2),/примерно 181/);assert.match(budgetPlan(.10),/ошибки и отмены/);assert.match(budgetPlan(.50,false),/выключены/);assert.match(budgetPlan(100),/Укажите предел/);assert.match(budgetPlan(0),/Укажите предел/);});

test('budget exhaustion cannot override explicit Stop or a reserved request still loading',()=>{const s={running:true,text_budget_exhausted:true};assert.equal(canShowExhaustion(s,false,false),true);assert.equal(canShowExhaustion(s,false,true),false);assert.equal(canShowExhaustion(s,true,false),false);assert.equal(canShowExhaustion({...s,running:false},false,false),false);});

test('estimated state uses declared maximum request reserve and never refunds by usage',()=>{const state={settings:{text_budget_usd:.5},text_reserved_usd:.1,estimated_text_usd:.0001,text_budget_policy:{kind:'estimated_v1',maximum_reservation_usd:.01104}};const before=structuredClone(state),label=budgetStatus(state);assert.match(label,/примерно 36/);assert.match(label,/не гарантированный предел счёта/);assert.deepEqual(state,before);});
