import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {fileURLToPath} from 'node:url';import {execFileSync} from 'node:child_process';
const file=fileURLToPath(import.meta.url),web=path.resolve(path.dirname(file),'../assets/web');
if(process.argv.includes('--probe')){
 const nodes=new Map(),listeners=new Map(),traces=[],calls=[];const get=id=>{if(!nodes.has(id))nodes.set(id,{value:'',textContent:'',dataset:{},checked:false,children:[],addEventListener(){},querySelectorAll(){return[]},replaceChildren(){},getBoundingClientRect(){return{top:0}},contains(){return false}});return nodes.get(id)};
 const document={getElementById:get,querySelectorAll:()=>[],activeElement:null};const window={calmMode:'live',calmMark:(stage,d)=>traces.push({stage,...d}),calmFocusStale:()=>{},addEventListener:(name,fn)=>listeners.set(name,fn)};
 const state={text_ready:true,running:true,settings:{},capture:{running:false}};const context=vm.createContext({window,document,performance:{now:()=>100},fetch:async url=>{calls.push(url);return{ok:true,json:async()=>url==='/api/personal-context'?{text:''}:state}},setInterval(){},setTimeout(){},Event:class{constructor(type){this.type=type}},AbortController});
 const modules=new Map();async function load(filename){if(modules.has(filename))return modules.get(filename);const m=new vm.SourceTextModule(fs.readFileSync(filename,'utf8'),{context,identifier:filename});modules.set(filename,m);await m.link(spec=>load(path.resolve(spec.startsWith('/')?web:path.dirname(filename),spec.startsWith('/')?spec.slice(1):spec)));return m;}
 await(await load(path.join(web,'integration.js'))).evaluate();await new Promise(r=>setImmediate(r));const observe=listeners.get('conversation-text');observe({detail:{synthetic:false,text:'Вы меня слышите?'}});const complete=window.calmReplyContext();observe({detail:{synthetic:false,text:'И ещё, если'}});await new Promise(r=>setImmediate(r));const pending=window.calmReplyContext();const last=traces.filter(e=>e.stage==='context_updated').at(-1);console.log(JSON.stringify({complete:complete?.latest_interlocutor_utterance.text,pending,last_context_characters:last?.characters,paid_or_post_calls:calls.filter(x=>x==='/api/text'||x==='/api/start').length}));
}else test('actual integration event invalidates old reply context immediately, before interval or request',()=>{const r=JSON.parse(execFileSync(process.execPath,['--experimental-vm-modules',file,'--probe'],{encoding:'utf8',stdio:['ignore','pipe','ignore']}));assert.equal(r.complete,'Вы меня слышите?');assert.equal(r.pending,null);assert.equal(r.last_context_characters,0);assert.equal(r.paid_or_post_calls,0);});
