import test from 'node:test';import assert from 'node:assert/strict';import {ConversationLedger,ReplyScheduler,SpeakerEvidence,canRunReplies} from '../assets/web/t9.js';
test('observed remote ledger preserves fragments, bounded context; own replies never inferred',()=>{const l=new ConversationLedger();l.observe('Вы мо',0);l.observe('жете пояснить условия? ',100);assert.equal(l.items[0].text,'Вы можете пояснить условия?');assert.equal(l.items[0].speaker,'unknown');assert(!l.context().includes('Я:'));for(let i=0;i<100;i++)l.observe('Новая существенная мысль. ',200+i);assert(l.context().length<=2400);assert(l.items.length<=30);});
test('unfinished pause may settle translated text but never identifies a human speaker',()=>{const l=new ConversationLedger();l.observe('Нужно уточнить детали этого плана',0);l.settle(1000);assert.equal(l.revision,0);l.settle(1700);assert.equal(l.revision,1);assert.equal(l.items[0].speaker,'unknown');});
test('automatic replies debounce, wait for pause, dedup, throttle, one inflight and discard any reply superseded by a completed segment',async()=>{let now=0,calls=0,resolve;const results=[],s=new ReplyScheduler({clock:()=>now,generate:()=>{calls++;return new Promise(r=>resolve=r);},onResult:r=>results.push(r)});s.configure(true);s.update('Собеседники: Уточните пожалуйста условия.',1,false);now=2000;assert.equal(await s.tick(),false);s.update(s.context,1,true);const first=s.tick();assert.equal(calls,1);await s.tick();assert.equal(calls,1);s.update('Собеседники: Другой важный вопрос.',2,true);resolve({options:[{en:'Please clarify.',ru:'Уточните.'}]});await first;assert.equal(results.length,0);now=3000;assert.equal(await s.tick(),false);now=4000;const second=s.tick();assert.equal(calls,2);resolve({options:[{en:'Which detail?',ru:'Какая деталь?'}]});await second;assert.equal(results.length,1);assert.equal(results[0].stale,false);now=30000;assert.equal(await s.tick(),false);});
test('Stop cancels pending/obsolete display; no automatic retry after failure or exhausted budget',async()=>{let now=0,calls=0,resolve;const results=[],s=new ReplyScheduler({clock:()=>now,generate:()=>{calls++;return new Promise(r=>resolve=r);},onResult:r=>results.push(r)});s.configure(true);s.update('Собеседники: Важная законченная реплика.',1,true);now=2000;const pending=s.tick();s.cancel();resolve({options:[]});await pending;assert.equal(results.length,0);now=20000;assert.equal(await s.tick(),false);assert.equal(calls,1);
 const f=new ReplyScheduler({clock:()=>now,generate:async()=>{calls++;throw Error('budget exhausted');},onResult:r=>results.push(r)});f.configure(true);f.update('Собеседники: Достаточный контекст.',1,true);now+=2000;await f.tick();now+=20000;await f.tick();assert.equal(calls,2);});
test('pause/punctuation cannot produce Speaker 1/2 labels without reliable channel/service evidence',()=>{const s=new SpeakerEvidence();assert.equal(s.label({speaker_id:'maybe1',evidence:'pause'}),'Собеседники');assert.equal(s.label({speaker_id:'a',evidence:'final_diarization'}),'Собеседник 1');assert.equal(s.label({speaker_id:'b',evidence:'isolated_channel'}),'Собеседник 2');assert.equal(s.label({speaker_id:'a',evidence:'final_diarization'}),'Собеседник 1');assert.equal(s.label({channel:'own_mic',evidence:'isolated_channel'}),'Я');});

test('last reserved paid result is shown once; exhausted budget prevents next call and Stop revokes display',async()=>{let now=0,resolve,calls=0;const results=[],s=new ReplyScheduler({clock:()=>now,generate:()=>{calls++;return new Promise(r=>resolve=r);},onResult:r=>results.push(r)});let state={running:true,text_ready:true,text_context_allowed:true,settings:{auto_suggestions:true}};s.configure(canRunReplies(state,s.busy));s.update('Собеседники: Уточните пожалуйста детали.',1,true);now=2000;const task=s.tick();state.text_ready=false;s.configure(canRunReplies(state,s.busy));resolve({options:[{en:'Which details?',ru:'Какие детали?'}]});await task;assert.equal(results.length,1);s.configure(canRunReplies(state,s.busy));now=20000;s.update('Собеседники: Ещё один вопрос.',2,true);await s.tick();assert.equal(calls,1);assert.equal(canRunReplies({...state,text_ready:true},false,true),false);});

test('settling an unfinished utterance uses one stabilization window, not two debounces',async()=>{let now=0,calls=0;const ledger=new ConversationLedger(),s=new ReplyScheduler({clock:()=>now,generate:async()=>{calls++;return {options:[{en:'Please clarify.',ru:'Уточните.'}]};},onResult:()=>{}});s.configure(true);ledger.observe('Объясните пожалуйста условия этого предложения',0);s.update(ledger.context(),ledger.version,true,ledger.lastDelta);now=1700;ledger.settle(now);s.update(ledger.context(),ledger.version,true,ledger.lastDelta);await s.tick();assert.equal(calls,1);});

 test('earlier result older than eight seconds is discarded, Stop always revokes it',async()=>{let now=0,resolve;const results=[],s=new ReplyScheduler({clock:()=>now,generate:()=>new Promise(r=>resolve=r),onResult:r=>results.push(r)});s.configure(true);s.update('Собеседники: Объясните пожалуйста расписание.',1,true);now=2000;const pending=s.tick();s.update('Собеседники: Теперь другой важный вопрос.',2,true);now=11000;resolve({options:[]});await pending;assert.equal(results.length,0);});

test('a completed meaningful sentence can trigger while interlocutor continues; per-delta requests stay bounded',async()=>{let now=0,calls=0;const ledger=new ConversationLedger(),s=new ReplyScheduler({clock:()=>now,generate:async()=>{calls++;return {options:[]};},onResult:()=>{}});s.configure(true);ledger.observe('Можете пояснить расписание? ',0);for(now=200;now<=2000;now+=200){ledger.observe('ещё ',now);s.update(ledger.context(),ledger.version,now-ledger.readyAt>=1600,ledger.readyAt);await s.tick();}assert.equal(calls,1);for(;now<11000;now+=200){ledger.observe('ещё ',now);s.update(ledger.context(),ledger.version,true,ledger.readyAt);await s.tick();}assert.equal(calls,1);});

test('Stop status survives both a delayed success and delayed provider failure',async()=>{for(const fail of [false,true]){let now=0,resolve,reject;const states=[],s=new ReplyScheduler({clock:()=>now,generate:()=>new Promise((a,b)=>{resolve=a;reject=b;}),onResult:()=>assert.fail('Stopped result displayed'),onState:state=>states.push(state)});s.configure(true);s.update('Собеседники: Важный завершённый вопрос.',1,true);now=2000;const pending=s.tick();s.cancel();if(fail)reject(Error('late network failure'));else resolve({options:[]});await pending;assert.equal(states.at(-1),'stopped');assert.equal(s.busy,false);assert.equal(await s.tick(),false);}});


test('partial continuation cannot invalidate the latest completed segment or create extra dispatches',async()=>{let now=0,resolve,calls=0;const ledger=new ConversationLedger(),results=[];const scheduler=new ReplyScheduler({clock:()=>now,generate:()=>{calls++;return new Promise(r=>resolve=r)},onResult:r=>results.push(r)});scheduler.configure(true);ledger.observe('Вы слышали? ',0);assert.equal(ledger.revision,1);now=750;scheduler.update(ledger.context(),ledger.revision,true,ledger.readyAt);const pending=scheduler.tick();const revision=ledger.revision;for(now=800;now<1800;now+=100){ledger.observe('продолжение ',now);scheduler.update(ledger.context(),ledger.revision,true,ledger.readyAt);await scheduler.tick()}assert.equal(ledger.revision,revision);resolve({options:[{en:'Could you repeat that?',ru:'Можете повторить?'}]});await pending;assert.equal(calls,1);assert.equal(results.length,1);assert.equal(results[0].stale,false)});

test('a new completed thought cancels stale display even if API returned within eight seconds',async()=>{let now=0,resolve;const ledger=new ConversationLedger(),results=[],trace=[];const scheduler=new ReplyScheduler({clock:()=>now,generate:()=>new Promise(r=>resolve=r),onResult:r=>results.push(r),onTrace:(stage,detail)=>trace.push({stage,...detail})});scheduler.configure(true);ledger.observe('Какой маршрут безопаснее? ',0);now=750;scheduler.update(ledger.context(),ledger.revision,true,ledger.readyAt);const pending=scheduler.tick();now=1000;ledger.observe('Что проверим перед стартом? ',now);scheduler.update(ledger.context(),ledger.revision,false,ledger.readyAt);now=1750;resolve({options:[]});await pending;assert.equal(results.length,0);assert(trace.some(x=>x.stage==='discard'&&x.reason==='new_completed_segment'));assert.equal(await scheduler.tick(),false)});

test('punctuated segments stabilize before full silence; quiet fragments still require 1600 ms',()=>{const ledger=new ConversationLedger(),trace=[];ledger.onTrace=(stage,detail)=>trace.push({stage,...detail});ledger.observe('Какой маршрут безопаснее? ',0);assert.equal(ledger.stabilization,600);ledger.observe('Нужно ещё уточнить условия',100);ledger.settle(1600);assert.equal(ledger.revision,1);ledger.settle(1700);assert.equal(ledger.revision,2);assert.equal(ledger.stabilization,1600);assert.equal(ledger.readyAt,100);assert.deepEqual(trace.map(x=>x.reason),['punctuation','quiet'])});

test('trace identifies debounce/rate limit and no same-context retry; does not include conversation text',async()=>{let now=0,calls=0;const trace=[];const s=new ReplyScheduler({clock:()=>now,generate:async()=>{calls++;return {options:[]}},onResult:()=>{},onTrace:(stage,detail)=>trace.push({stage,...detail})});s.configure(true);s.update('Собеседники: Какой маршрут?',1,true,0);now=500;await s.tick();now=750;await s.tick();s.update('Собеседники: Какие условия?',2,true,1000);now=2000;await s.tick();assert.equal(calls,1);assert(trace.some(x=>x.reason==='debounce'));assert(trace.some(x=>x.reason==='rate_limit'));now=12750;await s.tick();now=30000;await s.tick();assert.equal(calls,2);assert(trace.some(x=>x.reason==='already_attempted'));assert(!JSON.stringify(trace).includes('маршрут'))});

test('tiny adjacent questions remain distinct; decimal split across deltas stays one thought',()=>{const l=new ConversationLedger();l.observe('Где? ',0);l.observe('Как? ',100);assert.deepEqual(l.items.map(x=>x.text),['Где?','Как?']);l.observe('Стоимость 3.',200);assert.equal(l.revision,2);l.observe('5 доллара, а не 35. ',300);assert.equal(l.revision,3);assert.equal(l.items[2].text,'Стоимость 3.5 доллара, а не 35.');});
test('negation and self-correction supersede an inflight reply; early replacement is bounded',async()=>{let now=0,resolve,calls=0;const results=[],l=new ConversationLedger(),s=new ReplyScheduler({clock:()=>now,generate:()=>{calls++;return new Promise(r=>resolve=r)},onResult:r=>results.push(r)});s.configure(true);l.observe('Встречаемся в четверг. ',0);s.update(l.context(),l.revision,true,l.readyAt);now=750;let task=s.tick();now=1500;l.observe('Нет, не в четверг, а в пятницу. ',now);s.update(l.context(),l.revision,true,l.readyAt);now=2750;resolve({options:[]});await task;assert.equal(results.length,0);task=s.tick();assert.equal(calls,2);now=3000;l.observe('И не в пять, а в шесть. ',now);s.update(l.context(),l.revision,true,l.readyAt);now=4750;resolve({options:[]});await task;assert.equal(results.length,0);now=5000;assert.equal(await s.tick(),false);assert.equal(calls,2);now=13000;task=s.tick();assert.equal(calls,3);resolve({options:[{en:'What time exactly?',ru:'Во сколько именно?'}]});await task;assert.equal(results.length,1);assert(results[0].context.includes('не в пять'));});

test('failure of an obsolete request permits one bounded fresh replacement without retrying it',async()=>{let now=0,reject,calls=0;const s=new ReplyScheduler({clock:()=>now,generate:()=>{calls++;return calls===1?new Promise((_,r)=>reject=r):Promise.resolve({options:[]})},onResult:()=>{}});s.configure(true);s.update('Собеседники: Где?',1,true,0);now=750;const pending=s.tick();now=1500;s.update('Собеседники: Нет, где именно?',2,true,1500);now=2750;reject(Error('provider rejection'));await pending;await s.tick();assert.equal(calls,2);now=5000;await s.tick();assert.equal(calls,2);});

test('explicit latest target, bounded prior and unknown own response preserve short followups',()=>{const l=new ConversationLedger();l.observe('Когда нам уезжать? ',0);l.observe('Завтра? ',100);let c=l.replyContext();assert.equal(c.latest_interlocutor_utterance.text,'Завтра?');assert.equal(c.prior_context[0].text,'Когда нам уезжать?');assert.deepEqual(c.own_response_state,{spoken:'unknown',selected_draft_is_speech:false});l.observe('Цена 3.5 или 35 долларов? ',200);c=l.replyContext();assert.equal(c.latest_interlocutor_utterance.text,'Цена 3.5 или 35 долларов?');assert.equal(c.latest_interlocutor_utterance.segment_revision,l.revision);for(let i=0;i<10;i++)l.observe('Очень длинная предыдущая реплика '.repeat(50)+'? ',300+i);c=l.replyContext();assert(c.prior_context.length<=2);assert(c.prior_context.reduce((n,i)=>n+i.text.length,0)<=800);assert.equal(c.latest_interlocutor_utterance.text,l.items.at(-1).text);});
test('new completed thought after a shown result can replace early; sliding cap stays two',async()=>{let now=0,calls=0;const s=new ReplyScheduler({clock:()=>now,generate:async()=>{calls++;return {options:[]}},onResult:()=>{}});s.configure(true);s.update('Первый вопрос?',1,true,0);now=750;await s.tick();now=1500;s.update('Новая тема?',2,true,now);now=2750;await s.tick();assert.equal(calls,2);now=3500;s.update('Ещё новая тема?',3,true,now);now=5000;assert.equal(await s.tick(),false);assert.equal(calls,2);now=12750;await s.tick();assert.equal(calls,3)});
